name: CI Deploy to S3

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Lister les fichiers et dossiers
      run :  | #permet de séparer les commandes sur plusieurs lignes
        ls -la
    

    